### ISSUE TITLE
Issue mounting osxfuse on macOS 11 (Big-Sur BETA)

### ISSUE THREAD

**Issue by carlonzo** [whitewhidow/quest-sideloader-linux#23] opened 2020-10-30 12:51 UTC
receiving this when running quest-sideloader on macos 11.

`2020/10/30 13:55:51 Fatal error: failed to mount FUSE fs: exit status 1`

osx fuse should be supporting macos 11, but maybe better wait for https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0 to be available on brew?

**Comment by whitewhidow** [comment] 2020-10-30 13:54
> osx fuse should be supporting macos 11, but maybe better wait for https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0 to be available on brew?

aha,  yep,  hopefully they add it soon, in which case this might resolve itself at that point, if not, i guess i have some work to do ;)

**Comment by whitewhidow** [comment] 2020-11-01 16:47
have confirmed on another mac user which had the same issue, installing the osxfuse4 prerelease fixed it .

@carlonzo can you verify by chance?

**Comment by carlonzo** [comment] 2020-11-01 17:17
Sure thing

**Comment by whitewhidow** [comment] 2020-12-06 10:56
closing issue since development moved to 
https://github.com/whitewhidow/quest-sidenoder

**Closed by whitewhidow** 2020-12-06 10:56 UTC
