### ISSUE TITLE
error saying "drive mount seems to be missing or empty" (on osx)

### ISSUE THREAD

**Issue by carlonzo** [whitewhidow/quest-sideloader-linux#5] opened 2020-10-27 19:28 UTC
Hi when running the stable or development branch I receive this:
```
ERROR

Something is wrong, the drive mount seems to be missing or empty.
```

Also when I try to open the web-gui (when asked) the page is blank. Thanks for the hard work so far!! :)

**Comment by carlonzo** [comment] 2020-10-27 19:28
forgot to say, I'm on mac

**Comment by carlonzo** [comment] 2020-10-27 19:31
after few attempts, the web ui works temporary but then the process ends and the local webserver stops

**Comment by whitewhidow** [comment] 2020-10-27 20:50
Just to clarify, did you install via install.sh?
Also, make sure to pull the most recent verison, as i have done several updates today, and a large 2 hours ago)

Could you please post the output of the terminal window at the point of both failures:

1. the moment that the auto drivemount fails (before it auto suggests the webgui)
2. the moment the webgui fails (in case this also closes the terminal, and you cannot get to the output, please retry by manually running `whitewhidow-mount` as this will keep the terminal open after failing)

also, if you are on mac, see if installing OSXFUSE helps your case please (https://osxfuse.github.io/)

**Comment by buiyardee** [comment] 2020-10-28 05:26
Hi ive the same error, did the OSXFUSE install and restart but it seems to be unable to mount. It also doesnt open anything in chrome or other webbrowser. Do I need to type in a command. Sorry im new to all of this and took me a while just to understand what I needed to do just to install the software.

**Comment by whitewhidow** [comment] 2020-10-28 10:00
same question,   could you please paste the terminal output generated by `sideload-gui` during the point of failure, thx

**Comment by carlonzo** [comment] 2020-10-28 14:10
sorry for the late reply.

here are my terminal logs:

```
❯ curl -fsSL https://raw.githubusercontent.com/whitewhidow/quest-sideloader-linux/development/install.sh | /bin/bash -s -- development



====================================================================
= Quest(1/2) sideloader for Linux & Mac(OSX) =======================
====================================================================
========================================= by Whitewhidow/BranchBit =
===================================== support:contact@branchbit.be =
============================== https://t.me/whitewhidow_q2_working =
================ www.github.com/whitewhidow/quest-sideloader-linux =
====================================================================

CHECKING AND INSTALLING DEPENDENCIES:
Checking brew for mac.
Brew installed at /usr/local/bin/brew
Checking git installation.
Git installed at /usr/local/bin/git
Checking unzip installation.
Unzip installed at /usr/bin/unzip
Checking adb.
Adb installed at /Users/CarloMarinangeli/Library/Android/sdk/platform-tools/adb
Checking aapt.
Aapt installed at /Users/CarloMarinangeli/Library/Android/sdk/build-tools/29.0.2/aapt
Checking zenity.
Zenity installed at /usr/local/bin/zenity
Checking rclone.
Rclone installed at /usr/local/bin/rclone
Fetching newest version (development).
Cloning into 'quest-sideloader-linux'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 1363 (delta 85), reused 72 (delta 34), pack-reused 1220
Receiving objects: 100% (1363/1363), 8.87 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (810/810), done.
Branch 'development' set up to track remote branch 'development' from 'origin'.
Switched to a new branch 'development'
Copying executables to PATH (requires sudo)
Password:


 -> Install seems to have been successfull, you can now run 'sideload-gui' to open the sideloader.

 -> To self-update this package run 'sideload-update'.


Checking zenity installation.
Zenity installation found.
Attempting to serve the mount, Please wait.
just 2 more seconds, to make sure rclone had time to mount..
ls: /tmp/mnt/: No such file or directory
Still no mount, lets wait another 5..
ls: /tmp/mnt/: No such file or directory
```

here is the error in the dialog window instead:

```
ERROR

Something is wrong, the drive mount seems to be missing or empty.
if you report this at www.github.com/whitewhidow/quest-sideloader-linux, I will be happy to help

You can still use 'sideload-gui' to sideload apps you have manually downloaded

[NOTE] Since are on OSX, make sure you have OSXFUSE installed.
run 'brew cask install osxfuse' or go to https://osxfuse.github.io/ (this requires reboot, which is why we dont automate this)
```

I've installed osxfuse and reboot

**Comment by whitewhidow** [comment] 2020-10-28 15:40
Him thx for the output, the following 
`ls: /tmp/mnt/: No such file or directory`
seems to indicate that the previous commands `rm -r /tmp/mnt` and `mkdir-p /tmp/mnt` (removing and creating the folder in preperation of the mount) have also failed, and this is why the drive is not mounting

could you please run those 2 commands again, and then try `ls /tmp/mnt/` 

This should NOT return `ls: /tmp/mnt/: No such file or directory`, if it does, then this almost seems to be something machine/setup specific? As i have confirmed that this path (`/tmp/mnt`) should be fine for use on mac osx.

please verify this and let me know. Thank you for the feedback!

**Comment by carlonzo** [comment] 2020-10-28 16:57
you right.

so I just tried again running the script. no manual creation of the folder. failed but without the previous error in log.
tried again, this time the mount succeed. now I am really curious what caused the issues. will try to reboot and see if this repeats.

is there a way to enable more logs?
also, I've noticed that mounting the volume takes time to lead the folder structure. does it make sense to remove and remount if the volume is already mounted?

**Comment by whitewhidow** [comment] 2020-10-28 17:06
Hey,   yes please confirm if the reboot seemed to fix it or not.
Also, yes for some reason the list of folders take while on mac, whereas it is instant on linux :/  (remove and remount will not help i believe)
(CURRENTLY)  there is no way to make the logs more verbose (but you could temporarely manually remove the `2> /dev/null` parts in the scripts, in order to get stderr of the commands displayed in terminal instead of discarded.
I will add better logging shortly!!

**Comment by whitewhidow** [comment] 2020-10-29 09:45
@buiyardee 
@carlonzo 

i made some improvements to the part that does the mount detection.
Pease update to the and see let me know if this imporoves anything for you.

Thx

**Comment by carlonzo** [comment] 2020-10-29 14:32
just tried all good so far. will trie few more times and let you know if the problem is gone. Thanks!

**Comment by whitewhidow** [comment] 2020-10-29 16:47
GREAT !!

ps just merged into main a minute ago,  so good time to test !

**Comment by whitewhidow** [comment] 2020-10-29 18:09
If indeed resolved (and indeed *still* resolved *after* pulling latest version), then feel free to close the ticket.
Ps, More apps have been added to the cloud again today.

**Comment by buiyardee** [comment] 2020-10-29 18:30
Update didnt work for me, it made the 5 attempts and just stayed dare. Is it me are the app is resource hungry. Takes alot of time to start and every prompt takes a minute or 2. Making you wonder if it just crashed.

**Comment by whitewhidow** [comment] 2020-10-29 20:33
>  Takes alot of time to start and every prompt takes a minute or 2. Making you wonder if it just crashed.

this is obviously not normal ....    this install is actually pretty fast, the only thing it should be doing is (in case of mac), is install brew and a few brew packages, and even this, should only happen the first time, not the second time around, as you would already have them installed.

Ill make sure that in the next deploy, brew install actually shows its progress, instead of hiding it (hiding it is nicer, but makes people with slow pc's freak out ;)   )

(ps im in the process of renaming some stuff etc,  so best to just wait untill the open pr is merged later today, and then update)

also, please make a seperate ticket as this has zero todo with the content of this issue, thx

**Comment by whitewhidow** [comment] 2020-10-29 20:59
@carlonzo please use the following to update to the latest version (major changes)
```
curl -fsSL https://raw.githubusercontent.com/whitewhidow/quest-sideloader-linux/main/install | /bin/bash -s -- main

```
And let me know how it goes,   everything should be smooth for you (and the osx mount MIGHT be a bit faster to load now !!)

**Comment by carlonzo** [comment] 2020-10-30 10:01
do you really want me to try the `main` branch?

anyway tried both branches and worked fine! then I tried to switch to a virgin mac to try this from scratch. few points here:

- maybe brew install osxfuse automatically then stop the installation asking to reboot and allow the extension in terminal? before you actually go on?
- all the installation went smooth but then didnt mount as I guess this machine is on the macos 11 beta.

I tried then running `whitewhidow-mount /tmp/mnt` as you suggested in the other post and here I got 2 new logs:

`2020/10/30 13:55:46 NOTICE: macOS users: please try "rclone cmount" as it will be the default in v1.54`
`2020/10/30 13:55:51 Fatal error: failed to mount FUSE fs: exit status 1`

(I guess there are issues with fuse for macos beta :/ )

anyway on the previous machine everything keeps going smooth so I guess you can close. I will reopen if something happens? I can maybe open a separate issue for macos 11, as FYI

**Comment by whitewhidow** [comment] 2020-10-30 12:38
Gald to hear that you have it working !

sofcourse, feel free to open a seperate issue for both macos 11 beta related issues. ( i guesss ill be forced to tackle those soon anyway)

Thx !!!

**Closed by whitewhidow** 2020-10-30 12:38 UTC
Labels: bug
